version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80" # Host:Container

  backend:
    image: golang:tip-bullseye
    working_dir: /go/src/app
    volumes:
      - ./backend:/go/src/app
    ports:
      - "8081:8081"
    command: sh -c "go mod tidy && go run cmd/main.go"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=example
    depends_on:
      - db

  db:
    image: postgres:14.18
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: fullstack_docs
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres_data:
